trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - 'v*'

resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v2.0.0

jobs:
  - template: job--go-test.yml@asottile
    parameters:
      go_versions: ['1.15.2', '1.14.9']
      os: linux
      name_postfix: '_linux'